# Generated by Django 4.2.1 on 2023-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='upgrade',
            field=models.ManyToManyField(to='main_app.upgrade'),
        ),
    ]
